version: "3.9"

services:
  trb-officer-backend:
    container_name: trb-officer-backend
    build: ./
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8083:8080"
    env_file: 
      - .env